#!/usr/bin/env node
// Generate INDEX.md per axis under ~/code/work/.
// Reads each child folder's CLAUDE.md, extracts the first non-heading
// paragraph as a summary. Idempotent. Re-run after adding/renaming folders.
//
// Axes: systems, practices, capabilities (flat), accounts (subtype-nested).
// Excludes hidden dirs and any folder whose name starts with "_" (templates).

import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = '/Users/nplmini/code/work'
const SUMMARY_CAP = 240

// Extract the first non-heading paragraph that conveys the file's purpose.
// Skips any section whose H1 contains "context-mode" (the boilerplate routing
// block prepended to many CLAUDE.md files leaks otherwise).
function firstParagraph(claudeMdPath) {
  if (!existsSync(claudeMdPath)) return null
  const lines = readFileSync(claudeMdPath, 'utf8').split('\n')
  let skipping = false
  let started = false
  const para = []
  for (const raw of lines) {
    const line = raw.trim()
    const isH1 = /^#\s/.test(line) && !line.startsWith('## ')
    if (isH1) {
      if (started) break
      skipping = line.toLowerCase().includes('context-mode')
      continue
    }
    if (skipping) continue
    if (!line) {
      if (started) break
      continue
    }
    if (line.startsWith('#')) continue
    started = true
    para.push(line)
    if (para.join(' ').length > SUMMARY_CAP) break
  }
  const joined = para.join(' ').trim()
  if (!joined) return null
  return joined.length > SUMMARY_CAP ? joined.slice(0, SUMMARY_CAP - 1) + '…' : joined
}

function listChildDirs(parent) {
  if (!existsSync(parent)) return []
  return readdirSync(parent)
    .filter(name => !name.startsWith('.') && !name.startsWith('_'))
    .filter(name => statSync(join(parent, name)).isDirectory())
    .sort()
}

function entry(axisRel, name) {
  const dir = join(ROOT, axisRel, name)
  const claudeMd = join(dir, 'CLAUDE.md')
  let summary
  if (!existsSync(claudeMd)) {
    summary = '_no CLAUDE.md_'
  } else {
    summary = firstParagraph(claudeMd) || '_CLAUDE.md present but only context-mode boilerplate ... needs a purpose paragraph_'
  }
  const rel = `${axisRel}/${name}/CLAUDE.md`
  return [`### ${name}`, `Path: \`${rel}\``, '', summary, ''].join('\n')
}

function buildFlatAxis(axisName, headerNote) {
  const dirs = listChildDirs(join(ROOT, axisName))
  const out = []
  out.push(`# ${axisName} index`)
  out.push('')
  out.push(headerNote)
  out.push('')
  out.push('Generated by `scripts/generate-indexes.mjs`. Do not hand-edit.')
  out.push('')
  for (const d of dirs) out.push(entry(axisName, d))
  return out.join('\n')
}

function buildAccountsIndex() {
  const out = []
  out.push('# accounts index')
  out.push('')
  out.push('Engagements grouped by relationship type. Ventures = co-owned partnership businesses; clients = service engagements; prospects = pre-engagement context.')
  out.push('')
  out.push('Generated by `scripts/generate-indexes.mjs`. Do not hand-edit.')
  out.push('')
  for (const subtype of ['ventures', 'clients', 'prospects']) {
    const sub = join(ROOT, 'accounts', subtype)
    const dirs = listChildDirs(sub)
    if (!dirs.length) continue
    out.push(`## ${subtype}`)
    out.push('')
    for (const d of dirs) out.push(entry(`accounts/${subtype}`, d))
  }
  return out.join('\n')
}

const axes = [
  { name: 'systems', note: 'Each system is an indefinitely-operated agentic asset. Shared infra: canon-engine, revops-engine, projection-ui.' },
  { name: 'practices', note: 'Each practice is an operator persona plus its methodology. Launch Claude Code from a practice folder to load that persona.' },
  { name: 'capabilities', note: 'Shared building blocks (skills, schemas, reusable agents) usable by any system or practice.' },
]

for (const axis of axes) {
  const content = buildFlatAxis(axis.name, axis.note)
  const out = join(ROOT, axis.name, 'INDEX.md')
  writeFileSync(out, content)
  console.log(`wrote ${relative(ROOT, out)}`)
}

const accountsOut = join(ROOT, 'accounts', 'INDEX.md')
writeFileSync(accountsOut, buildAccountsIndex())
console.log(`wrote ${relative(ROOT, accountsOut)}`)
